### ISSUE TITLE
Talk about design of Item pages

### ISSUE THREAD

**Issue by lisagoff** [scholarslab/takeback#30]
http://takeback.neatline-uva.org/items/show/451
Looking at this page just as an example, I'm wondering if we can reconfigure the material here in several ways:
1. Make the order of info Description/Date/Tags/Subject headings/Related items. Which would mean changing the way the last 2 are currently worded (Subject, and Item relations). I don't think we need to list Collection (redundant) or Description (implicit, especially if we do #2).
   1. Put the image ("Files") adjacent to the Description, so that you don't have to scroll down to see it. And put the description right next to it. Description does not need a label--it should just appear at the top of the information, next to the image. And we don't need the label "Files" either, since it is intuitive to simply click on the image. 
      (If we have an item with multiple files/images, that becomes a issue, which we can discuss.)
   2. Also, I need to see the name of the publication next to the date. I need, in a glance, to know that the title of the item = the headline on the story, and to immediately see the name of the publication and the date. Is this possible? Imagine a typical researcher, who will be be taking a screen shot of this item, or a picture with their phone, or printing out a copy of the page. 
      I'm also wondering if we should have quotation marks around the titles, to make it clear that these are headlines--not titles we, the curators, have given to these items.  

Thoughts?

**Comment by jeremyboggs** [comment]
@lisagoff 

>Also, I need to see the name of the publication next to the date. I need, in a glance, to know that the title of the item = the headline on the story, and to immediately see the name of the publication and the date. Is this possible?

I'll need to look through several example items to see how this data was entered, to confirm whether it's possible as-is or if we'll need to edit some of the metadata to make this possible. Agreed it would be useful.

But while we're doing this, it would be useful, too, to look at other types of items and see whether we would want to follow similar formatting, _or_ if we would want to use unique formatting for those particular types.

> I'm also wondering if we should have quotation marks around the titles, to make it clear that these are headlines--not titles we, the curators, have given to these items.

If we're consistent about data entry, ideally we'd give these items a DC:Type of article, and dynamically put quotes around the title. I would prefer that way, instead of hand-entering quotes. This would also have the advantage of doing other formatting based on type, like bibliography entries, citations, etc...

**Comment by lisagoff** [comment]
This sounds like a good solution, Jeremy. Although I admit I'm not really
sure what it means to put quote "dynamically" around a title..
-Lisa
