### ISSUE TITLE
Colophon

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/takeback#6]
Add a colophon to the site that explains design and development decisions, including:
- Current Omeka setup
  - Theme
  - Plugins
  - Custom code

**Comment by emily-em** [comment]
I will add more aspects about research process to this and help create a form for the page

**Comment by emily-em** [comment]
For individual collections, should answer the following questions (for ourselves and for public narrative): How do we decide what constitutes a collection? Is there any consideration of the order in which the things themselves are collected? This process too tells a story about the evolution of access and priorities, particularly if this archive is intended to last, say 100 years. What is the lifespan of the archive? What is its explicit goal? Or, another thought, if this is intended to honor individual stories, is it helpful to separate collections around an individual and their experience? Where does the archive hope to expand?

**Comment by emily-em** [comment]
Also, have a section that acknowledges how much is NOT in the collection
Survivors who have not come forward for various reasons or whose records have been lost over time, especially likely underrepresentation of poc, queer and gender queer people, and men
Possible overrepresentation of college-related sexual violence due to research being located at the university and because of class privilege more generally

**Comment by emily-em** [comment]
This is done in project narrative now.
